remote_theme: giellalt/jekyll-theme-giellalt@main
title: Dictionary for Kildin Saami ⇒ Multiple languages
description: An electronic dictionary from Kildin Saami to Multiple languages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: default
